pipeline:

  build_image_pr:
    image: docker:17.09.0-ce
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
      - DOCKER_IMAGE=lev-api-test
    commands:
      - docker build -f ./test.Dockerfile -t "$${DOCKER_IMAGE}" .
    when:
      event: pull_request

  build_image_tag:
    image: docker:17.09.0-ce
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
      - DOCKER_IMAGE=lev-api-test
    commands:
      - docker build -f ./test.Dockerfile -t "$${DOCKER_IMAGE}:$${DRONE_TAG}" .
    when:
      event: tag

  push_image:
    image: docker:17.09.0-ce
    secrets:
      - docker_quay_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
      - DOCKER_IMAGE=lev-api-test
      - DOCKER_REPO=quay.io
      - DOCKER_BASEDIR=/ukhomeofficedigital/
      - DOCKER_USERNAME=ukhomeofficedigital+lev_api_spec
    commands:
      - docker login -u="$${DOCKER_USERNAME}" -p="$${DOCKER_QUAY_PASSWORD}" "$${DOCKER_REPO}"
      - ./publish.sh "$${DOCKER_IMAGE}:$${DRONE_TAG}" "$${DOCKER_REPO}$${DOCKER_BASEDIR}$${DOCKER_IMAGE}" "$${DRONE_TAG}"
    when:
      event: tag
