matrix:
  NAME:
    - docs
    - test
  NAME_PREFIX:
    - ukhomeofficedigital/lev-api-
  DOCKER_USERNAME:
    - ukhomeofficedigital+lev_api_spec
  DOCKER_REPO:
    - quay.io
pipeline:
  deps:
    image: quay.io/ukhomeofficedigital/lev-ci
    commands:
      - make deps-${NAME}
    when:
      event: [ pull_request, tag ]
  build_image:
    image: ukhomeoffice/drone-docker
    dockerfile: '${NAME}.Dockerfile'
    repo: '${DOCKER_REPO}/${NAME_PREFIX}${NAME}'
    dry_run: true
    when:
      event: pull_request
  push_image_to_quay:
    image: ukhomeoffice/drone-docker
    dockerfile: '${NAME}.Dockerfile'
    repo: '${DOCKER_REPO}/${NAME_PREFIX}${NAME}'
    auto_tag: true
    secrets: [ docker_password ]
    username: '${DOCKER_USERNAME}'
    registry: '${DOCKER_REPO}'
    when:
      event: tag
